package unicode.sinhala.keyboard

import unicode.sinhala.keyboard.SYMBOL

object Maps {

val wijesekaraMap: Map<String, CHAR> = mapOf(
    "a" to CHAR.SIGN_AL_LAKUNA,
    "A" to CHAR.GAYANUKITTA,
    "b" to CHAR.ALPAPRAANA_BAYANNA,
    "B" to CHAR.MAHAAPRAANA_BAYANNA,
    "c" to CHAR.ALPAPRAANA_DDAYANNA,
    "C" to CHAR.MAHAAPRAANA_DDAYANNA,
    "d" to CHAR.AELA_PILLA,
    "D" to CHAR.GAETTA_PILLA,
    "e" to CHAR.KETTI_AEDA_PILLA,
    "E" to CHAR.DIGA_AEDA_PILLA,
    "f" to CHAR.KOMBUVA,
    "F" to CHAR.FAYANNA,
    "g" to CHAR.ALPAPRAANA_TTAYANNA,
    "G" to CHAR.MAHAAPRAANA_TTAYANNA,
    "h" to CHAR.YAYANNA,
    "H" to CHAR.SIGN_YANSHAYA,
    "i" to CHAR.DANTAJA_SAYANNA,
    "I" to CHAR.MUURDHAJA_SAYANNA,
    "j" to CHAR.VAYANNA,
    "k" to CHAR.DANTAJA_NAYANNA,
    "K" to CHAR.MUURDHAJA_NAYANNA,
    "l" to CHAR.ALPAPRAANA_KAYANNA,
    "L" to CHAR.MAHAAPRAANA_KAYANNA,

    "m" to CHAR.DANTAJA_LAYANNA,
    "M" to CHAR.MUURDHAJA_LAYANNA,

    "n" to CHAR.ALPAPRAANA_PAYANNA,

    "N" to CHAR.MAHAAPRAANA_PAYANNA,

    "o" to CHAR.ALPAPRAANA_DAYANNA,
    "O" to CHAR.MAHAAPRAANA_DAYANNA,
    "p" to CHAR.ALPAPRAANA_CAYANNA,
    "P" to CHAR.MAHAAPRAANA_CAYANNA,
    "q" to CHAR.KETTI_PAA_PILLA,
    "Q" to CHAR.DIGA_PAA_PILLA,
    "r" to CHAR.RAYANNA,
    "R" to CHAR.IRUYANNA,
    "s" to CHAR.KETTI_IS_PILLA,
    "S" to CHAR.DIGA_IS_PILLA,
    "t" to CHAR.EYANNA,
    "T" to CHAR.OYANNA,
    "u" to CHAR.MAYANNA,
    "U" to CHAR.AMBA_BAYANNA,

    "v" to CHAR.IYANNA,
    "V" to CHAR.IIYANNA,

    "w" to CHAR.AYANNA,
    "W" to CHAR.UYANNA,
    "x" to CHAR.ALPAPRAANA_JAYANNA,
    "X" to CHAR.MAHAAPRAANA_JAYANNA,
    "y" to CHAR.HAYANNA,
    "Y" to CHAR.TAALUJA_SAYANNA,
    "z" to CHAR.ALPAPRAANA_TAYANNA,
    "." to CHAR.ALPAPRAANA_GAYANNA,
    ">" to CHAR.MAHAAPRAANA_GAYANNA,
    "," to CHAR.DANTAJA_LAYANNA,
    "<" to CHAR.MUURDHAJA_LAYANNA,
    ";" to CHAR.ALPAPRAANA_TAYANNA,
    ":" to CHAR.MAHAAPRAANA_TAYANNA,
    "1" to CHAR.SIGN_RAKARANSHAYA,
    "2" to CHAR.SIGN_REEPAYA,
    "3" to CHAR.SIGN_VISARGAYA,
    "4" to CHAR.SIGN_ANUSVARAYA,
    "5" to CHAR.TAALUJA_NAASIKYAYA,
    "6" to CHAR.TAALUJA_SANYOOGA_NAAKSIKYAYA,
    "7" to CHAR.SANYAKA_GAYANNA,
    "8" to CHAR.SANYAKA_JAYANNA,
    "9" to CHAR.SANYAKA_DDAYANNA,
    "0" to CHAR.SANYAKA_DAYANNA
)
val singlishMap: Map<String, CHAR> = mapOf(
    "a" to CHAR.AYANNA,
    "A" to CHAR.AEYANNA,
    "b" to CHAR.ALPAPRAANA_BAYANNA,
    "B" to CHAR.AMBA_BAYANNA,
    "c" to CHAR.ALPAPRAANA_CAYANNA,
    "C" to CHAR.MAHAAPRAANA_CAYANNA,
    "d" to CHAR.ALPAPRAANA_DDAYANNA,
    "D" to CHAR.MAHAAPRAANA_DDAYANNA,
    "e" to CHAR.EYANNA,
    "E" to CHAR.EEYANNA,
    "f" to CHAR.FAYANNA,
    "F" to CHAR.FAYANNA,
    "g" to CHAR.ALPAPRAANA_GAYANNA,
    "G" to CHAR.MAHAAPRAANA_GAYANNA,
    "h" to CHAR.HAYANNA,
    "H" to CHAR.HAYANNA,
    "i" to CHAR.IYANNA,
    "I" to CHAR.IIYANNA,
    "j" to CHAR.ALPAPRAANA_JAYANNA,
    "J" to CHAR.MAHAAPRAANA_JAYANNA,
    "k" to CHAR.ALPAPRAANA_KAYANNA,
    "K" to CHAR.MAHAAPRAANA_KAYANNA,
    "l" to CHAR.DANTAJA_LAYANNA,
    "L" to CHAR.MUURDHAJA_LAYANNA,
    "m" to CHAR.MAYANNA,
    "M" to CHAR.MAYANNA,
    "n" to CHAR.DANTAJA_NAYANNA,
    "N" to CHAR.MUURDHAJA_NAYANNA,
    "o" to CHAR.OYANNA,
    "O" to CHAR.OOYANNA,
    "p" to CHAR.ALPAPRAANA_PAYANNA,
    "P" to CHAR.MAHAAPRAANA_PAYANNA,
    "q" to CHAR.ALPAPRAANA_DAYANNA,
    "Q" to CHAR.MAHAAPRAANA_DAYANNA,
    "r" to CHAR.RAYANNA,
    "R" to CHAR.IRUYANNA,
    "s" to CHAR.DANTAJA_SAYANNA,
    "S" to CHAR.MUURDHAJA_SAYANNA,
    "t" to CHAR.ALPAPRAANA_TTAYANNA,
    "T" to CHAR.MAHAAPRAANA_TTAYANNA,
    "u" to CHAR.UYANNA,
    "U" to CHAR.UUYANNA,
    "v" to CHAR.VAYANNA,
    "V" to CHAR.VAYANNA,
    "w" to CHAR.VAYANNA,
    "W" to CHAR.VAYANNA,
    "x" to CHAR.SIGN_ANUSVARAYA,
    "X" to CHAR.SIGN_VISARGAYA,
    "y" to CHAR.YAYANNA,
    "Y" to CHAR.YAYANNA
)
val symbolsMap: Map<String, String> = mapOf(
    "q" to SYMBOL.LOW_LINE.text,
    "w" to SYMBOL.EXCLAMATION_MARK.text,
    "e" to SYMBOL.VERTICAL_LINE.text,
    "r" to SYMBOL.EQUALS_SIGN.text,
    "t" to SYMBOL.LEFT_SQUARE_BRACKET.text,
    "y" to SYMBOL.RIGHT_SQUARE_BRACKET.text,
    "u" to SYMBOL.LESS_THAN_SIGN.text,
    "i" to SYMBOL.GREATER_THAN_SIGN.text,
    "o" to SYMBOL.LEFT_CURLY_BRACKET.text,
    "p" to SYMBOL.RIGHT_CURLY_BRACKET.text,
    "a" to SYMBOL.COMMERCIAL_AT.text,
    "s" to SYMBOL.NUMBER_SIGN.text,
    "d" to SYMBOL.CIRCUMFLEX_ACCENT.text,
    "f" to SYMBOL.PERCENT_SIGN.text,
    "g" to SYMBOL.AMPERSAND.text,
    "h" to SYMBOL.HYPHEN_MINUS.text,
    "j" to SYMBOL.PLUS_SIGN.text,
    "k" to SYMBOL.LEFT_PARENTHESIS.text,
    "l" to SYMBOL.RIGHT_PARENTHESIS.text,
    "z" to SYMBOL.ASTERISK.text,
    "x" to SYMBOL.QUOTATION_MARK.text,
    "c" to SYMBOL.APOSTROPHE.text,
    "v" to SYMBOL.COLON.text,
    "b" to SYMBOL.SEMICOLON.text,
    "n" to SYMBOL.REVERSE_SOLIDUS.text,
    "m" to SYMBOL.QUESTION_MARK.text,
    "s1" to SYMBOL.SOLIDUS.text
)
val symbolsMapShifted: Map<String, String> = mapOf(
    "q" to SYMBOL.TILDE.text,
    "w" to SYMBOL.GRAVE_ACCENT.text,
    "e" to SYMBOL.SQUARE_ROOT.text,
    "r" to SYMBOL.GREEK_SMALL_LETTER_PI.text,
    "t" to SYMBOL.DIVISION_SIGN.text,
    "y" to SYMBOL.MULTIPLICATION_SIGN.text,
    "u" to SYMBOL.PILCROW_SIGN.text,
    "i" to SYMBOL.INCREMENT.text,
    "o" to SYMBOL.EURO_SIGN.text,
    "p" to SYMBOL.YEN_SIGN.text,
    "a" to SYMBOL.DOLLAR_SIGN.text,
    "s" to SYMBOL.POUND_SIGN.text,
    "d" to SYMBOL.CENT_SIGN.text,
    "f" to SYMBOL.DEGREE_SIGN.text,
    "g" to SYMBOL.COPYRIGHT_SIGN.text,
    "h" to SYMBOL.REGISTERED_SIGN.text,
    "j" to SYMBOL.TRADE_MARK_SIGN.text,
    "k" to SYMBOL.CARE_OF.text,
    "l" to SYMBOL.PLUS_MINUS_SIGN.text,
    "z" to SYMBOL.BULLET.text,
    "x" to SYMBOL.SOLIDUS.text,
    "c" to SYMBOL.CIRCLED_ZERO_WITH_SLASH.text,
    "v" to SYMBOL.CIRCLED_HUMAN_FIGURE.text,
    "b" to SYMBOL.CIRCLED_ANTICLOCKWISE_ARROW.text,
    "n" to SYMBOL.SOLIDUS.text,
    "m" to SYMBOL.CIRCLED_EQUALS.text,
    "s1" to SYMBOL.SOLIDUS.text
)

val keyLabelsLettersEnglish = mapOf(
    "a" to "a",
    "b" to "b",
    "c" to "c",
    "d" to "d",
    "e" to "e",
    "f" to "f",
    "g" to "g",
    "h" to "h",
    "i" to "i",
    "j" to "j",
    "k" to "k",
    "l" to "l",
    "m" to "m",
    "n" to "n",
    "o" to "o",
    "p" to "p",
    "q" to "q",
    "r" to "r",
    "s" to "s",
    "t" to "t",
    "u" to "u",
    "v" to "v",
    "w" to "w",
    "x" to "x",
    "y" to "y",
    "z" to "z"
)
val keyLabelsLettersEnglishShifted = mapOf(
    "a" to "A",
    "b" to "B",
    "c" to "C",
    "d" to "D",
    "e" to "E",
    "f" to "F",
    "g" to "G",
    "h" to "H",
    "i" to "I",
    "j" to "J",
    "k" to "K",
    "l" to "L",
    "m" to "M",
    "n" to "N",
    "o" to "O",
    "p" to "P",
    "q" to "Q",
    "r" to "R",
    "s" to "S",
    "t" to "T",
    "u" to "U",
    "v" to "V",
    "w" to "W",
    "x" to "X",
    "y" to "Y",
    "z" to "Z"
)
val keyLabelsLettersWijesekara: Map<String, String> = mapOf(
    "a" to CHAR.SIGN_AL_LAKUNA.text,
    "b" to CHAR.ALPAPRAANA_BAYANNA.text,
    "c" to CHAR.ALPAPRAANA_DDAYANNA.text,
    "d" to CHAR.AELA_PILLA.text,
    "e" to CHAR.KETTI_AEDA_PILLA.text,
    "f" to CHAR.KOMBUVA.text,
    "g" to CHAR.ALPAPRAANA_TTAYANNA.text,
    "h" to CHAR.YAYANNA.text,
    "i" to CHAR.DANTAJA_SAYANNA.text,
    "j" to CHAR.VAYANNA.text,
    "k" to CHAR.DANTAJA_NAYANNA.text,
    "l" to CHAR.ALPAPRAANA_KAYANNA.text,

    "m" to CHAR.DANTAJA_LAYANNA.text,
    "n" to CHAR.ALPAPRAANA_PAYANNA.text,

    "o" to CHAR.ALPAPRAANA_DAYANNA.text,
    "p" to CHAR.ALPAPRAANA_CAYANNA.text,
    "q" to CHAR.KETTI_PAA_PILLA.text,
    "r" to CHAR.RAYANNA.text,
    "s" to CHAR.KETTI_IS_PILLA.text,
    "t" to CHAR.EYANNA.text,
    "u" to CHAR.MAYANNA.text,
    "v" to CHAR.IYANNA.text,
    "w" to CHAR.AYANNA.text,
    "x" to CHAR.ALPAPRAANA_JAYANNA.text,
    "y" to CHAR.HAYANNA.text,
    "z" to CHAR.ALPAPRAANA_TAYANNA.text
)
val keyLabelsLettersWijesekaraShifted: Map<String, String> = mapOf(
    "a" to CHAR.GAYANUKITTA.text,
    "b" to CHAR.MAHAAPRAANA_BAYANNA.text,
    "c" to CHAR.MAHAAPRAANA_DDAYANNA.text,
    "d" to CHAR.GAETTA_PILLA.text,
    "e" to CHAR.DIGA_AEDA_PILLA.text,
    "f" to CHAR.FAYANNA.text,
    "g" to CHAR.MAHAAPRAANA_TTAYANNA.text,
    "h" to CHAR.SIGN_YANSHAYA.text,
    "i" to CHAR.MUURDHAJA_SAYANNA.text,
    "j" to CHAR.MUURDHAJA_LAYANNA.text + CHAR.KETTI_PAA_PILLA.text,
    "k" to CHAR.MUURDHAJA_NAYANNA.text,
    "l" to CHAR.MAHAAPRAANA_KAYANNA.text,
    "m" to CHAR.MUURDHAJA_LAYANNA.text,
    "n" to CHAR.MAHAAPRAANA_PAYANNA.text,
    "o" to CHAR.MAHAAPRAANA_DAYANNA.text,
    "p" to CHAR.MAHAAPRAANA_CAYANNA.text,
    "q" to CHAR.DIGA_PAA_PILLA.text,
    "r" to CHAR.IRUYANNA.text,
    "s" to CHAR.DIGA_IS_PILLA.text,
    "t" to CHAR.OYANNA.text,
    "u" to CHAR.AMBA_BAYANNA.text,
    "v" to CHAR.IIYANNA.text,
    "w" to CHAR.UYANNA.text,
    "x" to CHAR.MAHAAPRAANA_JAYANNA.text,
    "y" to CHAR.TAALUJA_SAYANNA.text,
    "z" to CHAR.MAHAAPRAANA_TAYANNA.text
)

val keyLabelsNumbers: Map<String, String> = mapOf(
    "1" to "1",
    "2" to "2",
    "3" to "3",
    "4" to "4",
    "5" to "5",
    "6" to "6",
    "7" to "7",
    "8" to "8",
    "9" to "9",
    "0" to "0"
)
val keyLabelsNumbersWijesekara: Map<String, String> = mapOf(
    "1" to CHAR.SIGN_RAKARANSHAYA.text,
    "2" to CHAR.SIGN_REEPAYA.text,
    "3" to CHAR.SIGN_VISARGAYA.text,
    "4" to CHAR.SIGN_ANUSVARAYA.text,
    "5" to CHAR.TAALUJA_NAASIKYAYA.text,
    "6" to CHAR.TAALUJA_SANYOOGA_NAAKSIKYAYA.text,
    "7" to CHAR.SANYAKA_GAYANNA.text,
    "8" to CHAR.SANYAKA_JAYANNA.text,
    "9" to CHAR.SANYAKA_DDAYANNA.text,
    "0" to CHAR.SANYAKA_DAYANNA.text
)

val keyLabelsSpecialEnglish: Map<String, String> = mapOf(
    "," to CHAR.COMMA.text,
    "." to CHAR.FULL_STOP.text
)
val keyLabelsSpecialWijesekara: Map<String, String> = mapOf(
    ";" to CHAR.SEMICOLON.text,
    "," to CHAR.COMMA.text,
    "." to CHAR.FULL_STOP.text
)
val keyLabelsSpecialWijesekaraShifted: Map<String, String> = mapOf(
    ";" to CHAR.COLON.text,
    "," to CHAR.LESS_THAN.text,
    "." to CHAR.GREATER_THAN.text
)
val keyLabelsSpecialWijesekaraSinhala: Map<String, String> = mapOf(
    ";" to CHAR.ALPAPRAANA_TAYANNA.text,
    "," to CHAR.DANTAJA_LAYANNA.text,
    "." to CHAR.ALPAPRAANA_GAYANNA.text
)
val keyLabelsSpecialWijesekaraSinhalaShifted: Map<String, String> = mapOf(
    ";" to CHAR.MAHAAPRAANA_TAYANNA.text,
    "," to CHAR.MUURDHAJA_LAYANNA.text,
    "." to CHAR.MAHAAPRAANA_GAYANNA.text
)

val helpMapWijesekara: List<Pair<String, String>> = listOf(
    "q" to CHAR.KETTI_PAA_PILLA.text,
    "Q" to CHAR.DIGA_PAA_PILLA.text,
    "w" to CHAR.AYANNA.text,
    "W" to CHAR.UYANNA.text,
    "e" to CHAR.KETTI_AEDA_PILLA.text,
    "E" to CHAR.DIGA_AEDA_PILLA.text,
    "r" to CHAR.RAYANNA.text,
    "R" to CHAR.IRUYANNA.text,
    "t" to CHAR.EYANNA.text,
    "T" to CHAR.OYANNA.text,
    "y" to CHAR.HAYANNA.text,
    "Y" to CHAR.TAALUJA_SAYANNA.text,
    "u" to CHAR.MAYANNA.text,
    "U" to CHAR.AMBA_BAYANNA.text,
    "i" to CHAR.DANTAJA_SAYANNA.text,
    "I" to CHAR.MUURDHAJA_SAYANNA.text,
    "o" to CHAR.ALPAPRAANA_DAYANNA.text,
    "O" to CHAR.MAHAAPRAANA_DAYANNA.text,
    "p" to CHAR.ALPAPRAANA_CAYANNA.text,
    "P" to CHAR.MAHAAPRAANA_CAYANNA.text,
    "a" to CHAR.SIGN_AL_LAKUNA.text,
    "A" to CHAR.GAYANUKITTA.text,
    "s" to CHAR.KETTI_IS_PILLA.text,
    "S" to CHAR.DIGA_IS_PILLA.text,
    "d" to CHAR.AELA_PILLA.text,
    "D" to CHAR.GAETTA_PILLA.text,
    "f" to CHAR.KOMBUVA.text,
    "F" to CHAR.FAYANNA.text,
    "g" to CHAR.ALPAPRAANA_TTAYANNA.text,
    "G" to CHAR.MAHAAPRAANA_TTAYANNA.text,
    "h" to CHAR.YAYANNA.text,
    "H" to CHAR.SIGN_YANSHAYA.text,
    "j" to CHAR.VAYANNA.text,
    "J" to CHAR.MUURDHAJA_LAYANNA.text + CHAR.KETTI_PAA_PILLA.text,
    "k" to CHAR.DANTAJA_NAYANNA.text,
    "K" to CHAR.MUURDHAJA_NAYANNA.text,
    "l" to CHAR.ALPAPRAANA_KAYANNA.text,
    "L" to CHAR.MAHAAPRAANA_KAYANNA.text,
    ";" to CHAR.ALPAPRAANA_TAYANNA.text,
    ":" to CHAR.MAHAAPRAANA_TAYANNA.text,
    "x" to CHAR.SIGN_ANUSVARAYA.text,
    "X" to CHAR.KANTAJA_NAASIKYAYA.text,
    "c" to CHAR.ALPAPRAANA_JAYANNA.text,
    "C" to CHAR.MAHAAPRAANA_JAYANNA.text,
    "v" to CHAR.ALPAPRAANA_DDAYANNA.text,
    "V" to CHAR.MAHAAPRAANA_DDAYANNA.text,
    "b" to CHAR.IYANNA.text,
    "B" to CHAR.IIYANNA.text,
    "n" to CHAR.ALPAPRAANA_BAYANNA.text,
    "N" to CHAR.MAHAAPRAANA_BAYANNA.text,
    "m" to CHAR.ALPAPRAANA_PAYANNA.text,
    "M" to CHAR.MAHAAPRAANA_PAYANNA.text,
    "," to CHAR.DANTAJA_LAYANNA.text,
    "<" to CHAR.MUURDHAJA_LAYANNA.text,
    "." to CHAR.ALPAPRAANA_GAYANNA.text,
    ">" to CHAR.MAHAAPRAANA_GAYANNA.text
)

val helpMapSinglish: List<Pair<String, String>> = listOf(
    CHAR.AYANNA.text to "a",
    CHAR.AAYANNA.text to "aa",
    CHAR.AEYANNA.text to "A",
    CHAR.AEEYANNA.text to "Aa",
    CHAR.IYANNA.text to "i",
    CHAR.IIYANNA.text to "ii / I",
    CHAR.UYANNA.text to "u",
    CHAR.UUYANNA.text to "uu / U",
    CHAR.IRUYANNA.text to "R",
    CHAR.IRUUYANNA.text to "Ri",
    CHAR.EYANNA.text to "e",
    CHAR.EEYANNA.text to "ee / E",
    CHAR.AIYANNA.text to "ai",
    CHAR.OYANNA.text to "o",
    CHAR.OOYANNA.text to "oo / O",
    CHAR.AUYANNA.text to "au",
    CHAR.SIGN_ANUSVARAYA.text to "x",
    CHAR.SIGN_VISARGAYA.text to "X",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "k",
    CHAR.MAHAAPRAANA_KAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "kh / K",
    CHAR.ALPAPRAANA_GAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "g",
    CHAR.MAHAAPRAANA_GAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "gh / G",
    CHAR.KANTAJA_NAASIKYAYA.text + CHAR.SIGN_AL_LAKUNA.text to "",
    CHAR.SANYAKA_GAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "zg",
    CHAR.ALPAPRAANA_CAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "gh / G",
    CHAR.MAHAAPRAANA_CAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "c",
    CHAR.MAHAAPRAANA_GAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "ch / C",
    CHAR.ALPAPRAANA_JAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "j",
    CHAR.MAHAAPRAANA_JAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "jh / J",
    CHAR.TAALUJA_NAASIKYAYA.text + CHAR.SIGN_AL_LAKUNA.text to "zk",
    CHAR.SANYAKA_JAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "zj",
    CHAR.ALPAPRAANA_TTAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "t",
    CHAR.MAHAAPRAANA_TTAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "T",
    CHAR.ALPAPRAANA_DDAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "d",
    CHAR.MAHAAPRAANA_DDAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "D",
    CHAR.MUURDHAJA_NAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "N",
    CHAR.SANYAKA_DDAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "zD",
    CHAR.ALPAPRAANA_TAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "th",
    CHAR.MAHAAPRAANA_TAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "thh / Th",
    CHAR.ALPAPRAANA_DAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "dh / q",
    CHAR.MAHAAPRAANA_DAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "dhh / Dh / qh / Q",
    CHAR.DANTAJA_NAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "n",
    CHAR.SANYAKA_DAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "zdh",
    CHAR.ALPAPRAANA_PAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "p",
    CHAR.MAHAAPRAANA_PAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "ph / P",
    CHAR.ALPAPRAANA_BAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "b",
    CHAR.MAHAAPRAANA_BAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "bh / B",
    CHAR.MAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "m",
    CHAR.AMBA_BAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "zb",
    CHAR.YAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "y",
    CHAR.RAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "r",
    CHAR.DANTAJA_LAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "l",
    CHAR.VAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "v / w",
    CHAR.TAALUJA_SAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "sh",
    CHAR.MUURDHAJA_SAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "S / Sh",
    CHAR.DANTAJA_SAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "S",
    CHAR.HAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "h",
    CHAR.MUURDHAJA_LAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "L",
    CHAR.FAYANNA.text + CHAR.SIGN_AL_LAKUNA.text to "f / F",
    CHAR.TAALUJA_SANYOOGA_NAAKSIKYAYA.text + CHAR.SIGN_AL_LAKUNA.text to "zh",
    "" to "",
    CHAR.ALPAPRAANA_KAYANNA.text to "ka",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.AELA_PILLA.text to "kaa",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.KETTI_AEDA_PILLA.text to "kA",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.DIGA_AEDA_PILLA.text to "kAa",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.KETTI_IS_PILLA.text to "ki",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.DIGA_IS_PILLA.text to "kii / kI",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.KETTI_PAA_PILLA.text to "ku",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.DIGA_PAA_PILLA.text to "kuu / kU",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.GAETTA_PILLA.text to "kR",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.DIGA_GAETTA_PILLA.text to "kRi",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.KOMBUVA.text to "ke",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.DIGA_KOMBUVA.text to "kee / kE",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.KOMBU_DEKA.text to "kai",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.KOMBUVA_HAA_AELA_PILLA.text to "ko",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.KOMBUVA_HAA_DIGA_AELA_PILLA.text to "koo / kO",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.KOMBUVA_HAA_GAYANUKITTA.text to "kau",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.SIGN_ANUSVARAYA.text to "kax",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.SIGN_VISARGAYA.text to "kaX",
    "" to "",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.SIGN_YANSHAYA.text + CHAR.SIGN_AL_LAKUNA.text to "ky / kY",
    CHAR.ALPAPRAANA_KAYANNA.text + CHAR.SIGN_RAKARANSHAYA.text + CHAR.SIGN_AL_LAKUNA.text to "kr"
)

}
